name: Continuous Integration

on:
  push:
    branches: ['**']

jobs:
  build:
    name: 'Lint, Build & Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install packages
        run: npm install

      - name: Lint
        run: npm run lint:ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
